version: '2'
services:
 auth_bypass1_yaml:
   restart: always
#   image: tutum/lamp:latest
   build:
       context: ./Docker/
       dockerfile: Dockerfile
   container_name: auth_bypass1_yaml
   ports:
    - "5003:5000"
#   volumes:
#    - "./php.ini:/etc/php5/apache2/php.ini"
#    - "./PbootCMS-custom/:/var/www/html"